# Default values for ingestion.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ankurgos/ingestion
  tag: test
  pullPolicy: Always

# Path to directory to ingest. This will be mounted inside the docker instance at /input
pdfDir: /Users/ankur/Projects/Mask-RCNN-exp/cosmos/data/test_docs
#pdfDir: /Users/ankur/Projects/Mask-RCNN-exp/services/ingestion/tests/pdfs

mongouser: root
mongopwd: password
mongourl: cosmos-mongodb.default.svc.cluster.local
mongoport: 27017

nameOverride: ""
fullnameOverride: ""

