version: "2.3"
services:
    postprocess:
        build: .
        ipc: host
        command: "python3 postprocess.py 30 pp_model_weights.pth"
        #volumes:
        #    - .:/cosmos/
        #    - ${INPUT_DIR}:/input/
        #    - ${OUTPUT_DIR}:/output/
        environment:
            - DBCONNECT
