version: "2.3"
services:
    aggregate_sections:
        build: .
        ipc: host
        #volumes:
        #    - .:/develop/
        command: "python3 aggregate.py 30 --no-section --no-equation --figure --table"
        environment:
            - DBCONNECT
        
        

